"""SQL generation utilities for connector installation."""

import re
from typing import Any, Optional

_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _validate_identifier(name: str, kind: str) -> str:
    """Validate SQL identifiers to prevent SQL injection."""
    if not _IDENTIFIER_RE.match(name):
        raise ValueError(f"Invalid {kind} identifier: {name}")
    return name


def _escape_sql_string(value: str) -> str:
    """Escape SQL string literal value."""
    return value.replace("'", "''")


def _choose_dollar_quote_tag(python_code: str) -> str:
    """Pick a dollar-quote tag that does not conflict with connector code."""
    for tag in ("$tp$", "$ctf$", "$pycode$"):
        if tag not in python_code:
            return tag

    index = 1
    while index < 100000:
        tag = f"$tp{index}$"
        if tag not in python_code:
            return tag
        index += 1

    raise ValueError("Unable to choose a safe SQL dollar quote tag")


def generate_install_sql(
    manifest: dict[str, Any],
    stream_name: Optional[str] = None,
) -> str:
    """
    Generate installation SQL from a connector manifest.

    Args:
        manifest: The connector manifest dictionary
        stream_name: Optional custom stream name (defaults to connector name)

    Returns:
        Ready-to-execute SQL string
    """
    metadata = manifest["metadata"]
    spec = manifest["spec"]

    # Use provided name or default from manifest (convert hyphens to underscores)
    name = _validate_identifier(stream_name or metadata["name"].replace("-", "_"), "stream")
    namespace = metadata["namespace"]
    version = metadata["version"]
    category = spec["category"]
    mode = spec["mode"]

    # Build column definitions
    columns = ", ".join(
        [
            f"{_validate_identifier(col['name'], 'column')} {col['type']}"
            for col in spec["schema"]["columns"]
        ]
    )

    # Build SETTINGS clause
    settings_parts = ["type='python'", f"mode='{_escape_sql_string(mode)}'"]

    functions = spec.get("functions", {})
    if functions.get("read"):
        read_name = _validate_identifier(functions["read"]["name"], "function")
        settings_parts.append(f"read_function_name='{_escape_sql_string(read_name)}'")

    if functions.get("write"):
        write_name = _validate_identifier(functions["write"]["name"], "function")
        settings_parts.append(f"write_function_name='{_escape_sql_string(write_name)}'")

    settings_str = ", ".join(settings_parts)

    # Build dependency installation
    dependencies = spec.get("dependencies", [])
    deps_sql = "\n".join(
        [
            f"SYSTEM INSTALL PYTHON PACKAGE '{_escape_sql_string(dep)}';"
            for dep in dependencies
        ]
    )

    if not deps_sql:
        deps_sql = "-- No Python dependencies required"

    # Get Python code
    python_code = spec["pythonCode"]
    quote_tag = _choose_dollar_quote_tag(python_code)

    # Build the complete SQL
    sql_lines = [
        f"-- Timeplus Connector: {namespace}/{metadata['name']}@{version}",
        f"-- Category: {category} | Mode: {mode}",
        "-- Generated by Timeplus Connector Registry",
        "",
        "-- Step 1: Install Python dependencies",
        deps_sql,
        "",
        "-- Step 2: Create the external stream",
        f"CREATE EXTERNAL STREAM {name}({columns})",
        f"AS {quote_tag}",
        python_code,
        quote_tag,
        f"SETTINGS {settings_str};",
        "",
        "-- Usage:",
    ]

    # Add usage comments based on category
    if category in ["source", "bidirectional"]:
        sql_lines.append(f"-- Read:  SELECT * FROM {name};")

    if category in ["sink", "bidirectional"]:
        sql_lines.append(f"-- Write: INSERT INTO {name} VALUES (...);")

    return "\n".join(sql_lines)


def generate_uninstall_sql(stream_name: str) -> str:
    """
    Generate SQL to remove a connector.

    Args:
        stream_name: The stream name to remove

    Returns:
        SQL string to drop the stream
    """
    stream = _validate_identifier(stream_name, "stream")
    return f"DROP STREAM IF EXISTS {stream};"
