"""SQL generation utilities for connector installation."""

from typing import Any, Optional


def generate_install_sql(
    manifest: dict[str, Any],
    stream_name: Optional[str] = None,
) -> str:
    """
    Generate installation SQL from a connector manifest.

    Args:
        manifest: The connector manifest dictionary
        stream_name: Optional custom stream name (defaults to connector name)

    Returns:
        Ready-to-execute SQL string
    """
    metadata = manifest["metadata"]
    spec = manifest["spec"]

    # Use provided name or default from manifest (convert hyphens to underscores)
    name = stream_name or metadata["name"].replace("-", "_")
    namespace = metadata["namespace"]
    version = metadata["version"]
    category = spec["category"]
    mode = spec["mode"]

    # Build column definitions
    columns = ", ".join(
        [f"{col['name']} {col['type']}" for col in spec["schema"]["columns"]]
    )

    # Build SETTINGS clause
    settings_parts = [f"type='python'", f"mode='{mode}'"]

    functions = spec.get("functions", {})
    if functions.get("read"):
        settings_parts.append(f"read_function_name='{functions['read']['name']}'")

    if functions.get("write"):
        settings_parts.append(f"write_function_name='{functions['write']['name']}'")

    settings_str = ", ".join(settings_parts)

    # Build dependency installation
    dependencies = spec.get("dependencies", [])
    deps_sql = "\n".join([f"SYSTEM INSTALL PYTHON PACKAGE '{dep}';" for dep in dependencies])

    if not deps_sql:
        deps_sql = "-- No Python dependencies required"

    # Get Python code
    python_code = spec["pythonCode"]

    # Build the complete SQL
    sql_lines = [
        f"-- Timeplus Connector: {namespace}/{metadata['name']}@{version}",
        f"-- Category: {category} | Mode: {mode}",
        f"-- Generated by Timeplus Connector Registry",
        "",
        "-- Step 1: Install Python dependencies",
        deps_sql,
        "",
        "-- Step 2: Create the external stream",
        f"CREATE EXTERNAL STREAM {name}({columns})",
        "AS $$",
        python_code,
        "$$",
        f"SETTINGS {settings_str};",
        "",
        "-- Usage:",
    ]

    # Add usage comments based on category
    if category in ["source", "bidirectional"]:
        sql_lines.append(f"-- Read:  SELECT * FROM {name};")

    if category in ["sink", "bidirectional"]:
        sql_lines.append(f"-- Write: INSERT INTO {name} VALUES (...);")

    return "\n".join(sql_lines)


def generate_uninstall_sql(stream_name: str) -> str:
    """
    Generate SQL to remove a connector.

    Args:
        stream_name: The stream name to remove

    Returns:
        SQL string to drop the stream
    """
    return f"DROP STREAM IF EXISTS {stream_name};"
