apiVersion: v1
kind: Connector

metadata:
  name: coinbase-websocket-read-connector
  namespace: timeplus
  version: "1.0.5"
  displayName: Coinbase WebSocket Read Connector
  description: |
    Reads real-time market data from the Coinbase Exchange WebSocket feed.
    Requires sending a subscription message after connecting.
  authors:
    - name: Timeplus Dev
      email: dev@timeplus.com
  license: Apache-2.0

spec:
  category: source
  mode: streaming
  
  tags:
    - websocket
    - coinbase
    - exchange
    - crypto
    - market-data
    - real-time
  
  compatibility:
    protonVersion: ">=3.0.0"
    pythonVersion: ">=3.9"
  
  dependencies:
    - websocket-client>=1.4.0
    - json5>=0.9.6 # For more flexible JSON parsing
  
  schema:
    columns:
      - name: type
        type: string
        nullable: true
        description: The type of message received (e.g., 'subscriptions', 'l2update', 'ticker').
      - name: product_id
        type: string
        nullable: true
        description: The product ID related to the message (e.g., 'BTC-USD').
      - name: channel
        type: string
        nullable: true
        description: The channel of the message (e.g., 'l2_data', 'ticker').
      - name: full_payload
        type: string
        nullable: false
        description: The full raw JSON payload of the message.
      - name: received_at
        type: datetime64(3)
        nullable: false
        description: The timestamp when the message was received by the connector.
  
  functions:
    read:
      name: read_coinbase_websocket_stream
      description: Connects to Coinbase WebSocket, subscribes, and yields messages.

  configTemplate:
    - name: websocket_url
      description: The URL of the Coinbase WebSocket endpoint.
      example: wss://ws-feed.exchange.coinbase.com
      defaultValue: wss://ws-feed.exchange.coinbase.com
      location: pythonCode
    - name: subscription_message
      description: The JSON message to send to subscribe to channels/products.
      example: '{"type": "subscribe", "product_ids": ["BTC-USD", "ETH-USD"], "channels": ["level2", "ticker"]}'
      defaultValue: '{"type": "subscribe", "product_ids": ["BTC-USD"], "channels": ["ticker"]}'
      location: pythonCode

  pythonCode: |
    import websocket
    import json5
    import time
    from datetime import datetime

    def read_coinbase_websocket_stream():
        websocket_url = "wss://ws-feed.exchange.coinbase.com"
        subscription_message = '{"type": "subscribe", "product_ids": ["BTC-USD"], "channels": ["ticker"]}'

        ws = None
        while True:
            try:
                ws = websocket.create_connection(websocket_url)
                ws.send(subscription_message)

                while True:
                    message = ws.recv() or ""
                    parsed_message = json5.loads(message) or {}

                    msg_type = parsed_message.get("type") or ""
                    product_id = parsed_message.get("product_id") or ""

                    channel_name = ""
                    channels = parsed_message.get("channels")
                    if msg_type == "subscriptions" and channels:
                        channel_name = ", ".join([c.get("name", "unknown") for c in channels]) or ""
                    elif "channel" in parsed_message:
                        channel_name = parsed_message.get("channel") or ""

                    yield (
                        msg_type,
                        product_id,
                        channel_name,
                        message,
                        datetime.utcnow(),
                    )

            except Exception:
                time.sleep(5)
            finally:
                if ws:
                    ws.close()
            time.sleep(1)

  examples:
    - title: Read Default Coinbase Ticker Data
      description: Retrieve ticker messages for BTC-USD (using default subscription).
      code: |
        SELECT type, product_id, channel, full_payload, received_at
        FROM timeplus_builtin.coinbase_websocket_read_connector;

    - title: Filter for Level2 Updates (custom subscription)
      description: Focus on real-time order book (level2) updates for BTC-USD.
      code: |
        SELECT 
          received_at,
          JSONExtractString(full_payload, '$.product_id') AS product,
          JSONExtractString(full_payload, '$.type') AS message_type,
          JSONExtractString(full_payload, '$.changes[0][0]') AS side, -- 'buy' or 'sell'
          JSONExtractString(full_payload, '$.changes[0][1]') AS price,
          JSONExtractString(full_payload, '$.changes[0][2]') AS size
        FROM timeplus_builtin.coinbase_websocket_read_connector
        WHERE type = 'l2update';

    - title: Aggregate Ticker Prices for ETH-USD
      description: Calculate the approximate average last trade price from ETH-USD ticker messages over 5-second windows.
      code: |
        SELECT 
          window_start() as window_start_time,
          avg(CAST(JSONExtractString(full_payload, '$.price') AS float64)) AS average_price
        FROM timeplus_builtin.coinbase_websocket_read_connector
        WHERE type = 'ticker'
        GROUP BY window_start()
        WINDOW tumbling(5s);