apiVersion: v1
kind: Connector

metadata:
  name: kafka-json-reader
  namespace: timeplus
  version: 1.0.0
  displayName: Kafka JSON Reader
  description: |
    Read JSON messages from a Kafka topic as a streaming source.
    Pre-configured for a specific broker and topic - customize the Python code
    before deploying.
  authors:
    - name: Timeplus Team
      email: support@timeplus.com
  license: Apache-2.0
  homepage: https://github.com/timeplus-io/connectors
  repository: https://github.com/timeplus-io/connectors
  documentation: https://docs.timeplus.com/connectors/kafka

spec:
  category: source
  mode: streaming
  
  tags:
    - kafka
    - json
    - streaming
    - message-queue
    - apache
  
  compatibility:
    protonVersion: ">=3.0.0"
    pythonVersion: ">=3.9"
  
  dependencies:
    - kafka-python>=2.0.2
  
  schema:
    columns:
      - name: value
        type: int32
        description: The parsed integer value from JSON message

  functions:
    read:
      name: py_kafka_read
      description: Read and parse JSON messages from Kafka topic

  configTemplate:
    - name: bootstrap_servers
      description: Kafka broker addresses (comma-separated for multiple brokers)
      example: "k1:9092"
      location: "Line 7 in pythonCode"
    - name: topic
      description: Kafka topic name to consume from
      example: "py_read"
      location: "Line 6 in pythonCode"
    - name: group_id
      description: Consumer group ID for offset tracking
      example: "py_kafka_read_probe"
      location: "Line 9 in pythonCode"
    - name: auto_offset_reset
      description: Where to start consuming (earliest or latest)
      example: "earliest"
      location: "Line 8 in pythonCode"

  pythonCode: |
    from kafka import KafkaConsumer
    import json
    
    def py_kafka_read():
        consumer = KafkaConsumer(
            "py_read",
            bootstrap_servers="k1:9092",
            auto_offset_reset="earliest",
            enable_auto_commit=True,
            group_id="py_kafka_read_probe",
            value_deserializer=lambda m: json.loads(m.decode("utf-8")),
        )
        try:
            for msg in consumer:
                yield [msg.value["value"]]
        finally:
            consumer.close()

  examples:
    - title: Basic Read
      description: Read all messages from the configured Kafka topic
      code: |
        SELECT * FROM kafka_json_reader;
    
    - title: Filtered Read
      description: Read messages with value greater than threshold
      code: |
        SELECT * FROM kafka_json_reader 
        WHERE value > 100;
    
    - title: Aggregation
      description: Count messages by value ranges
      code: |
        SELECT 
          floor(value / 10) * 10 as range_start,
          count(*) as count
        FROM kafka_json_reader
        GROUP BY range_start;
